/*
 *  Licensed Materials - Property of IBM
 *  5725-I43 (C) Copyright IBM Corp. 2011, 2013. All Rights Reserved.
 *  US Government Users Restricted Rights - Use, duplication or
 *  disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
 */

function startProcess(cliente) {
	/*SOAP Envelope generated by SoapUI */	
	var request = '<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ws="http://RFPRCSS/WS.tws" xmlns:bap="http://BAPPT">'		
		+ '  <soapenv:Header/>'
		+ '  <soapenv:Body>'
		+ '     <ws:crearCliente>'
		+ '        <ws:cliente>'
		+ '          <bap:nombre>'+cliente.nombre+'</bap:nombre>'
		+ '          <bap:apellido> '+cliente.apellido+'</bap:apellido>'
		+ '          <bap:cedula>'+cliente.cedula+'</bap:cedula>'
		+ '          <bap:direccion>'+cliente.direccion+'</bap:direccion>'
		+ '          <bap:fechaNacimiento>'+cliente.fechaNacimiento+'</bap:fechaNacimiento>'
		+ '          <bap:password>'+cliente.password+'</bap:password>'
		+ '        </ws:cliente>'
		+ '     </ws:crearCliente>'
		+ ' </soapenv:Body>'
		+ '</soapenv:Envelope>';

	var path = "teamworks/webservices/RFPRCSS/WS.tws";
	var input = {
		method : 'post',
		returnedContentType : 'xml',
		path : path,
		headers : {
			'SOAPAction' : 'http://RFPRCSS/WS.tws/crearCliente'
		},
		body : {
			content : request,
			contentType : 'text/xml; charset=utf-8'
		}
	};
	WL.Logger.debug("start process  " + request);
	response = WL.Server.invokeHttp(input);
}
